# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-15 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0002_dojo_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='info',
            field=models.TextField(default='No info'),
        ),
    ]
